### PR TITLE
Fixed cocoapods integration with use_frameworks!.

### PR DESCRIPTION
**Pull request by dmorrow**
This should solve issue #9

### CODE REVIEW

**Comment by f2prateek** [comment]
Can you clarify how this fixes the issue?

**Comment by dmorrow** [comment]
Including the GA library in the .h file, rather than the .m triggers the 'non-modular header' error when compiling for swift.

**Comment by f2prateek** [comment]
How are you getting around the 'target has transitive dependencies that include static binaries' error in the first place?

**Comment by dmorrow** [comment]
@f2prateek Using this method from https://github.com/segment-integrations/analytics-ios-integration-google-analytics/issues/3#issuecomment-209758430

**Comment by dmorrow** [comment]
#4 seems to be an acceptable solution to this issue as well

**Comment by dmorrow** [comment]
@wcjohnson11 Can this be merged?  We can't move forward with updating our Segment because of this issue.

**Review by f2prateek — APPROVED** [review]

**Pull request merged**
