### PR TITLE
Fix SEGGoogleAnalyticsIntegrationFactory singleton type

### PR DESCRIPTION
**Pull request by jPaolantonio**

### CODE REVIEW

**Comment by f2prateek** [comment]
Yikes! Mind updating the `+ (id)instance` to return `SEGIntegrationFactory` as well?

**Comment by jPaolantonio** [comment]
@f2prateek I'll do it.

**Comment by jPaolantonio** [comment]
@f2prateek I updated code to return `SEGGoogleAnalyticsIntegrationFactory`, but could use `instanceType` if you prefer.

**Comment by f2prateek** [comment]
oh haha yeah `instanceType` would actually be better!

**Comment by jPaolantonio** [comment]
@f2prateek `instanceType` is now implemented.

**Comment by f2prateek** [comment]
Thanks!

**Pull request merged**
